[zram0]
zram-size = ram * 1.6
compression-algorithm = zstd
swap-priority = 100
fs-type = swap

[zram1]
zram-size = ram * 0.2
compression-algorithm = zstd
mount-point = /tmp
fs-type = ext4

[zram2]
zram-size = ram * 0.1
compression-algorithm = zstd
mount-point = /var/log
fs-type = ext4
